package:
    name: pyart
    version: 1.6.0

source:
    fn: arm_pyart-1.6.0.tar.gz
    url: https://pypi.python.org/packages/source/a/arm_pyart/arm_pyart-1.6.0.tar.gz
    md5: 6c382dda78193c730a6a47d2d7b18eeb

build:
    number: 0

requirements:
    build:
        - python
        - numpy
        - trmm_rsl

    run:
        - python
        - numpy
        - scipy
        - matplotlib
        - netcdf4
        - trmm_rsl

test:
    imports:
        - pyart

about:
    home: http://arm-doe.github.io/pyart/
    license: BSD
