package:
    name: pyart
    version: 1.3.0

source:
    fn: arm_pyart-1.3.0.tar.gz
    url: https://pypi.python.org/packages/source/a/arm_pyart/arm_pyart-1.3.0.tar.gz
    md5: e40fd8696b014d76043466c5735c4417

build:
    number: 0

requirements:
    build:
        - python
        - numpy
        - trmm_rsl

    run:
        - python
        - numpy
        - scipy
        - matplotlib
        - netcdf4

test:
    imports:
        - pyart

about:
    home: http://arm-doe.github.io/pyart/
    license: BSD
